//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplySet
    {
        public int id { get; set; }
        public int idAgent { get; set; }
        public int idClient { get; set; }
        public int idRealEstate { get; set; }
        public Nullable<long> Price { get; set; }
    
        public virtual Agentset Agentset { get; set; }
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual RealEstateSet RealEstateSet { get; set; }
    }
}
